---
#
# Ansible managed
#
repository:
  description: Install and enable remi yum repositories on your system.
  homepage: https://robertdebock.nl/
  topics: remi, ansible, molecule, tox, playbook, hacktoberfest
