---
language: python

python:
  - "3.7"

services:
  - docker

env:
  matrix:
    - distribution="alpine:latest"
    - distribution="alpine:edge"
    - distribution="archlinux/base"
    - distribution="robertdebock/docker-centos-systemd:7"
    - distribution="robertdebock/docker-centos-systemd:latest"
    - distribution="robertdebock/docker-debian-systemd:latest"
    - distribution="robertdebock/docker-debian-systemd:stable"
    - distribution="robertdebock/docker-debian-systemd:unstable"
    - distribution="robertdebock/docker-fedora-systemd:latest"
    - distribution="robertdebock/docker-fedora-systemd:rawhide"
    - distribution="opensuse/leap"
    - distribution="robertdebock/docker-ubuntu-systemd:latest"
    - distribution="robertdebock/docker-ubuntu-systemd:devel"
    - distribution="robertdebock/docker-ubuntu-systemd:rolling"

matrix:
  allow_failures:
    - env: distribution="alpine:edge"
    - env: distribution="robertdebock/docker-debian-systemd:unstable"
    - env: distribution="robertdebock/docker-fedora-systemd:rawhide"
    - env: distribution="robertdebock/docker-ubuntu-systemd:devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install molecule
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "MChklVpLwwy7eHr1cV76C62cr/bdp1wHwZaJpfDMWkN+DkyJpupsxygAeALanlwvANUsMuc+I2lwhLqaSwKo292FSkA6bV0kNQoDha3A0Y9tftYz165i8GS93W8HNUY1V+yrmFPxkpzEmmDK+jkDGzv4w3Z79HVEsZPs+pHd7aQgbwrNq/cOS5wG4SZG6vVH9ctXrA5kQGUsUWd2HNVaJn1cr1naQ71Sa5Y0IKGsNXfrsJpZLWy/WZ2MLVfmGKlD3/6FhvAtdLWLvakyE4YcN4smOgMgiA5xr2zPHK6+KpDaGXxcdcavKDynNxbQkqV2GTm9MupIH9Qu6LCiKpKfi8XNGLMmwyh8DmOFPoqfmYGAJbFJF/J3iAI4xKVsWv2AL+pE7MRnyKVxFaqcBreIA9FEXAJxflf0kVs0BDbljZm3SnynHJWLTe83D99CchpZKiwphCTtinIzKgiEHx6TlBIjWGhVGRvVssFS4o3rKJoS9eeV8OHX3nJF6nIg08EAnpIcA5aCNYbZceummUcihWmtSKRHXIRq/aqhJ4dEzS9lXBaBkPZmpQDLAV3zFUTDzaCW5kxNNoH7NBKP4keFs8so/6WlGP3s4uwZbcHUg3SknkF6zRIfVUrUy6TiKDgv45GzS51JZnnUpD9dkwTWJQ0dYnYRaQSHzNzLGWmBevI="
  email: false
