---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="7"
    - image="redhat" tag="7"
    - image="centos"
    - image="redhat"

matrix:
  allow_failures:

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "MChklVpLwwy7eHr1cV76C62cr/bdp1wHwZaJpfDMWkN+DkyJpupsxygAeALanlwvANUsMuc+I2lwhLqaSwKo292FSkA6bV0kNQoDha3A0Y9tftYz165i8GS93W8HNUY1V+yrmFPxkpzEmmDK+jkDGzv4w3Z79HVEsZPs+pHd7aQgbwrNq/cOS5wG4SZG6vVH9ctXrA5kQGUsUWd2HNVaJn1cr1naQ71Sa5Y0IKGsNXfrsJpZLWy/WZ2MLVfmGKlD3/6FhvAtdLWLvakyE4YcN4smOgMgiA5xr2zPHK6+KpDaGXxcdcavKDynNxbQkqV2GTm9MupIH9Qu6LCiKpKfi8XNGLMmwyh8DmOFPoqfmYGAJbFJF/J3iAI4xKVsWv2AL+pE7MRnyKVxFaqcBreIA9FEXAJxflf0kVs0BDbljZm3SnynHJWLTe83D99CchpZKiwphCTtinIzKgiEHx6TlBIjWGhVGRvVssFS4o3rKJoS9eeV8OHX3nJF6nIg08EAnpIcA5aCNYbZceummUcihWmtSKRHXIRq/aqhJ4dEzS9lXBaBkPZmpQDLAV3zFUTDzaCW5kxNNoH7NBKP4keFs8so/6WlGP3s4uwZbcHUg3SknkF6zRIfVUrUy6TiKDgv45GzS51JZnnUpD9dkwTWJQ0dYnYRaQSHzNzLGWmBevI="
  email: false
