---
# tasks file for remi
- name: include assert.yml
  include_tasks: assert.yml

- name: install remi repository
  package:
    name: "{{ remi_repository }}"
    state: present
    disable_gpg_check: yes
  notify:
    - reset php stream
    - enable repository
  when:
    - ansible_distribution in [ "CentOS", "Fedora", "RedHat" ]
