---
# tasks file for remi
- name: include assert.yml
  include_tasks: assert.yml

- name: install remi repository
  package:
    name: "{{ remi_repository }}"
    state: present
  when:
    - ansible_pkg_mgr == "yum"
    - ansible_distribution == "CentOS" or
      ansible_distribution == "RedHat"

- name: trust remi key
  rpm_key:
    key: "{{ remi_repository_key }}"
    state: present
  when:
    - ansible_pkg_mgr == "yum"
    - ansible_distribution == "CentOS" or
      ansible_distribution == "RedHat"

- name: enable selected remi repository
  lineinfile:
    path: /etc/yum.repos.d/remi-{{ item }}.repo
    regexp: '^enabled='
    line: 'enabled=1'
  when:
    - ansible_pkg_mgr == "yum"
    - ansible_distribution == "CentOS" or
      ansible_distribution == "RedHat"
    - remi_enabled_repositories is defined
  loop: "{{ remi_enabled_repositories }}"
