---
# tasks file for remi
- name: include assert.yml
  include_tasks: assert.yml

- name: trust remi key
  rpm_key:
    key: "{{ remi_repository_key }}"
    state: present
  when:
    - ansible_distribution in [ "CentOS", "Fedora", "RedHat" ]

- name: install remi repository
  package:
    name: "{{ remi_repository }}"
    state: present
  notify:
    - reset php stream
    - enable repository
  when:
    - ansible_distribution in [ "CentOS", "Fedora", "RedHat" ]
