---
# handlers file for remi

- name: reset php stream
  command: dnf --assumeyes module reset php
  when:
    - ansible_pkg_mgr == "dnf"

- name: enable repository
  command: "{{ remi_enable_repository_command }}"
