---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  vars:
    _remi_verify_package:
      Fedora: php-gd
      CentOS: &verify_package php81-php-gd
      Rocky: *verify_package
    remi_verify_package: "{{ _remi_verify_package[ansible_distribution] }}"

  tasks:
    - name: Install php
      ansible.builtin.package:
        name: php
        state: present

    - name: Verify the version of php
      ansible.builtin.command:
        cmd: php --version
      register: remi_version_of_php
      failed_when:
        - "'PHP 8.1' not in remi_version_of_php.stdout"

    - name: Install a package from the remi repository
      ansible.builtin.package:
        name: "{{ remi_verify_package }}"
